export const GET_PRODUCTS_REQUEST = "GET_PRODUCTS_REQUEST"
export const GET_PRODUCTS_SUCCESS = "GET_PRODUCTS_SUCCESS"
export const GET_PRODUCTS_FAIL = "GET_PRODUCTS_FAIL"

export const GET_PRODUCT_DETAILS_REQUEST = "GET_PRODUCT_DETAILS_REQUEST"
export const GET_PRODUCT_DETAILS_SUCCESS = "GET_PRODUCT_DETAILS_SUCCESS"
export const GET_PRODUCT_DETAILS_FAIL = "GET_PRODUCT_DETAILS_FAIL"
export const GET_PRODUCT_DETAILS_RESET = "GET_PRODUCT_DETAILS_RESET"

export const GET_IDEAS_REQUEST = "GET_IDEAS_REQUEST"
export const GET_IDEAS_SUCCESS = "GET_IDEAS_SUCCESS"
export const GET_IDEAS_FAIL = "GET_IDEAS_FAIL"

export const GET_COLLECTIONS_REQUEST = "GET_COLLECTIONS_REQUEST"
export const GET_COLLECTIONS_SUCCESS = "GET_COLLECTIONS_SUCCESS"
export const GET_COLLECTIONS_FAIL = "GET_COLLECTIONS_FAIL"
export const FILTER = "FILTER"

export const ADD_PRODUCTS_FAIL = "ADD_PRODUCTS_FAIL"
export const ADD_PRODUCTS_SUCCESS = "ADD_PRODUCTS_SUCCESS"